# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Math-Calc-Units
version:      1.06
version_from: Units.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
license:      perl
recommends:
  Time::Local: 0
no_index: Parse::Yapp::Driver
